### ISSUE TITLE
Transform.py doesn't support MultiLineString

### ISSUE THREAD

**Issue by james2432** [osmottawa/etl2osm#12]
MultiLineString is present in the Lake-County_Roads and is not implemented
This is a blocker for #2 
```
C:\komodo>C:\Python34\python3.4.exe cli.py "C:\Florida\Lake-County_Roads_WGS84.shp" --output testing.osm --config="C:\etl2osm\sources\roads\lake_county.json"
Traceback (most recent call last):
  File "cli.py", line 59, in <module>
    cli()
  File "C:\Python34\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python34\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "C:\Python34\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python34\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "cli.py", line 51, in cli
    process(infile, **kwargs)
  File "C:\komodo\api.py", line 19, in process
    load(data,infile=infile,outfile=kwargs["output"],**kwargs)
  File "C:\komodo\api.py", line 49, in load
    Load(data, **kwargs)
  File "C:\komodo\load.py", line 38, in __init__
    write_file[extension](data, outfile, config, **kwargs)
  File "C:\komodo\load.py", line 79, in write_osm
    feature = reproject(feature, data.crs_wkt, 4326)
  File "C:\komodo\transform.py", line 31, in reproject
    raise ValueError('Reproject geometry type not implemented: %s' % geom['type'])
ValueError: Reproject geometry type not implemented: MultiLineString
```

**Comment by DenisCarriere** [comment]
Yep I saw this coming :P lol! That's why it raises that error. I'll follow the GeoJSON schema and keep tackling those geometry types.

I'm sure someone has made a library for it, one of them is "shapely" but I'm just going to follow the GeoJSON specs, I like that schema better.

**Comment by james2432** [comment]
If you wish to test it out i put the code under write_osm branch code is functional, but incomplete
