### ISSUE TITLE
Handling Null Geometry

### ISSUE THREAD

**Issue by DenisCarriere** [osmottawa/etl2osm#18]
denis@denis:~/Downloads/roads_201411131541259796$ etl2osm Roads8_2014.shp --config sumter_county.json --outfile roads.osm
WARNING:root:Suffix cannot be found [BAY] in ETL2OSM models.
WARNING:root:Direction cannot be found [s] in ETL2OSM models.
Traceback (most recent call last):
  File "/usr/local/bin/etl2osm", line 9, in <module>
    load_entry_point('etl2osm==0.0.1', 'console_scripts', 'etl2osm')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/denis/Github/etl2osm/etl2osm/cli.py", line 14, in cli
    etl2osm.process(infile, config, outfile)
  File "/home/denis/Github/etl2osm/etl2osm/api.py", line 16, in process
    data.transform(config)
  File "/home/denis/Github/etl2osm/etl2osm/extract.py", line 152, in transform
    feature = reproject(feature, self.crs, osr.SRS_WKT_WGS84)
  File "/home/denis/Github/etl2osm/etl2osm/transform.py", line 78, in reproject
    coord = feature['geometry']['coordinates']
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by DenisCarriere** [comment]
Surprisingly easy fix, already closed...
